name = "aitattoogenerator"
main = "worker.js"
compatibility_date = "2026-05-30"

[[d1_databases]]
binding = "D1"
database_name = "aitattoogenerator-db"
database_id = "4de6be41-380d-42b0-a9f5-758235519594"

[[r2_buckets]]
binding = "R2"
bucket_name = "aitattoogenerator-images"

[[queues.producers]]
binding = "AI_QUEUE"
queue = "aitattoogenerator-ai-queue"
